window.env = {
  "TERM_PROGRAM": "vscode",
  "NODE": "/usr/local/bin/node",
  "INIT_CWD": "/Users/jacoporodighiero/Desktop/buynomics-test-jacopo",
  "SHELL": "/bin/zsh",
  "TERM": "xterm-256color",
  "TMPDIR": "/var/folders/1d/1t1jt4w12ld98jvxd2ty7s580000gn/T/",
  "npm_config_metrics_registry": "https://registry.npmjs.org/",
  "TERM_PROGRAM_VERSION": "1.64.0",
  "ORIGINAL_XDG_CURRENT_DESKTOP": "undefined",
  "COLOR": "1",
  "npm_config_noproxy": "",
  "USER": "jacoporodighiero",
  "COMMAND_MODE": "unix2003",
  "npm_config_globalconfig": "/usr/local/etc/npmrc",
  "SSH_AUTH_SOCK": "/private/tmp/com.apple.launchd.WVF9V1D1Mp/Listeners",
  "__CF_USER_TEXT_ENCODING": "0x1F5:0x0:0x2",
  "npm_execpath": "/usr/local/lib/node_modules/npm/bin/npm-cli.js",
  "PATH": "/Users/jacoporodighiero/Desktop/buynomics-test-jacopo/node_modules/.bin:/Users/jacoporodighiero/Desktop/node_modules/.bin:/Users/jacoporodighiero/node_modules/.bin:/Users/node_modules/.bin:/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/node-gyp-bin:/Users/jacoporodighiero/Desktop/buynomics-test-jacopo/node_modules/.bin:/Users/jacoporodighiero/Desktop/node_modules/.bin:/Users/jacoporodighiero/node_modules/.bin:/Users/node_modules/.bin:/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/node-gyp-bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin",
  "_": "/Users/jacoporodighiero/Desktop/buynomics-test-jacopo/node_modules/.bin/react-dotenv",
  "npm_package_json": "/Users/jacoporodighiero/Desktop/buynomics-test-jacopo/package.json",
  "__CFBundleIdentifier": "com.microsoft.VSCode",
  "npm_config_init_module": "/Users/jacoporodighiero/.npm-init.js",
  "npm_config_userconfig": "/Users/jacoporodighiero/.npmrc",
  "PWD": "/Users/jacoporodighiero/Desktop/buynomics-test-jacopo",
  "npm_command": "run-script",
  "EDITOR": "vi",
  "npm_lifecycle_event": "build",
  "LANG": "en_GB.UTF-8",
  "npm_package_name": "buynomics-test-jacopo",
  "XPC_FLAGS": "0x0",
  "VSCODE_GIT_ASKPASS_EXTRA_ARGS": "--ms-enable-electron-run-as-node",
  "npm_config_node_gyp": "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js",
  "XPC_SERVICE_NAME": "0",
  "npm_package_version": "0.1.0",
  "HOME": "/Users/jacoporodighiero",
  "SHLVL": "3",
  "VSCODE_GIT_ASKPASS_MAIN": "/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js",
  "LOGNAME": "jacoporodighiero",
  "npm_config_cache": "/Users/jacoporodighiero/.npm",
  "npm_lifecycle_script": "react-dotenv && react-scripts build",
  "VSCODE_GIT_IPC_HANDLE": "/var/folders/1d/1t1jt4w12ld98jvxd2ty7s580000gn/T/vscode-git-7c3ff21d74.sock",
  "npm_config_user_agent": "npm/7.18.1 node/v14.16.0 darwin x64 workspaces/false",
  "GIT_ASKPASS": "/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass.sh",
  "VSCODE_GIT_ASKPASS_NODE": "/Applications/Visual Studio Code.app/Contents/MacOS/Electron",
  "COLORTERM": "truecolor",
  "npm_config_prefix": "/usr/local",
  "npm_node_execpath": "/usr/local/bin/node"
};